[package]
name = "libguestfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
libc = "0.2.141"
libguestfs-sys = { path = "../libguestfs-sys" }
